[package]
name = "fibonacci_generator"
version = "0.1.0"
authors = ["Michael Berry <trismegustis@gmail.com>"]
edition = "2018"

[lib]
name = "fibonacci"
path = "src/lib.rs"

[[bin]]
name = "fibonacci-interactive"
path = "src/fibonacci-interactive.rs"

[dependencies]
